# Generated by Django 4.1.2 on 2022-10-29 06:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Продукт')),
                ('category', models.CharField(choices=[('electronics', 'Электроника'), ('cars', 'Автомобили'), ('drones', 'Дроны')], max_length=150, verbose_name='Категория')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Фото продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='Отзыв')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Значение не может быть более 5'), django.core.validators.MinValueValidator(limit_value=1, message='Значение не может быть менее 1')], verbose_name='Оценка')),
                ('author', models.ManyToManyField(related_name='review_authors', to=settings.AUTH_USER_MODEL, verbose_name='Авторы, оставившие отзывы')),
                ('product', models.ManyToManyField(related_name='reviewed_products', to='webapp.product', verbose_name='Продукты, получившие отзывы')),
            ],
        ),
    ]
